### ISSUE TITLE
Intrinsics

### ISSUE THREAD

**Issue by RomanovMikeV** [diode-dataset/diode-devkit#1]
Hi! Thanks for your work, it is a very interesting dataset for such an important problem!

I wonder, is it possible somehow to get the good approximation of intrinsics of the camera that this dataset was taken with?

It may be crucial for some tasks and not that hard to evaluate using the checkerboard printed pattern.

Best regards.

**Comment by w-hc** [comment]
@ivasiljevic has uploaded a txt file describing the intrinsics.
