### ISSUE TITLE
Will you provide extrinsics parameters of cameras?

### ISSUE THREAD

**Issue by wangys8363** [diode-dataset/diode-devkit#4]
Hi, thanks for providing this dataset. Besides intrinsics parameters, will you also provide the extrinsics parameters of the cameras?

**Comment by ivasiljevic** [comment]
the camera and lidar are coaxial so no extrinsic calibration necessary. For a given scan, the frames are all taken from the same point, so translation is zero, and the camera rotation can be obtained from file names (azimuth/elevation)
